import java.net.URI

plugins {
    `java-library`
    `maven-publish`

    alias(libs.plugins.shadow)
    alias(libs.plugins.lombok)
}

group = "gg.hoglin"
version = System.getenv("VERSION") ?: "dev"

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.unirest.core)
    implementation(libs.unirest.jackson)
    implementation(libs.slf4j)
    implementation(libs.commons.codec)
    compileOnly(libs.jetbrains.annotations)
    compileOnly(libs.autoservice)
    annotationProcessor(libs.autoservice)
}

java {
    withSourcesJar()
    withJavadocJar()
}

tasks.javadoc {
    val options = options as StandardJavadocDocletOptions
    options.addStringOption("tag", "apiNote:a:API Note:")
    options.addStringOption("Xdoclint:none", "-quiet") // to really suppress all the doc errors

    // Needed to suppress errors caused by Lombok autogenerated members
    isFailOnError = false
}

tasks.build {
    dependsOn(tasks.shadowJar)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "$group"
            artifactId = "sdk"
            version = "$version"
            artifact(tasks.shadowJar.get().archiveFile)
            artifact(tasks.named("sourcesJar").get())
            artifact(tasks.named("javadocJar").get())
        }
    }

    repositories {
        maven {
            name = "Hoglin"
            url = URI("https://maven.hoglin.gg/releases")
            credentials {
                username = findProperty("repo.waypoint.username") as String? ?: System.getenv("REPO_USER")
                password = findProperty("repo.waypoint.password") as String? ?: System.getenv("REPO_PASS")
            }
        }
    }
}
